version: 2.1

orbs:
  dwave: dwave/orb-examples@dev:c2d912e

workflows:
  version: 2.1
  tests:
    jobs:
      - dwave/test-linux
      - dwave/test-osx
      - dwave/test-win

  weekly:
    triggers:
      - schedule:
          cron: "0 2 * * 5"
          filters:
            branches:
              only:
                - master
                - main
    jobs:
      - dwave/test-linux
      - dwave/test-osx
      - dwave/test-win
